"""Replenishment module.
Computes per-store SKU shortfalls and generates transfer orders
to satisfy hurricane prep plans using synthetic demo data.
"""
from __future__ import annotations
from dataclasses import dataclass, asdict
from datetime import datetime, timezone
from math import cos, radians, sqrt, atan2, sin
from . import HURRICANE_SKUS, DISTRIBUTION_CENTERS, ITEM_TO_SKUS, nearest_dc
from .synthetic import prior_season_sales, current_inventory, dc_inventory

SAFETY_FACTOR = 1.2  # target_units = prior_season_sold * 1.2


@dataclass(frozen=True)
class Shortfall:
    dest_osm_id: str
    dest_name: str
    dest_county: str | None
    dest_fips: str | None
    sku_id: str
    sku_name: str
    item: str
    unit: str
    prior_season_sold: int
    target_units: int
    on_hand: int
    shortfall_units: int
    urgency: str          # the store's time_bucket from the prep plan


@dataclass
class TransferOrder:
    to_id: str            # 'TO-0001' style; generated by caller's index
    source_type: str      # 'DC' or 'STORE'
    source_id: str
    source_name: str
    dest_osm_id: str
    dest_name: str
    dest_county: str | None
    sku_id: str
    sku_name: str
    units: int
    urgency: str
    status: str           # initially 'awaiting_approval'
    created_at: str       # UTC iso8601
    rationale: str        # one short sentence explaining the routing choice


def compute_shortfalls(prep_plan: list[dict], all_stores: list[dict],
                       hurricane_risk_by_fips: dict[str, float]) -> list[Shortfall]:
    '''For every store in the prep plan, compute per-SKU shortfalls.

    Each prep_plan entry has at least: osm_id, name, county, fips,
    stock_checklist (list of item names), time_bucket.
    Each store dict in all_stores has the same shape — used to look up by fips.
    hurricane_risk_by_fips maps a county FIPS -> 0..1 hurricane risk score.
    '''
    # For SKU lookups, build a dict sku_id -> SKU object up front.
    sku_by_id = {s.id: s for s in HURRICANE_SKUS}
    # County population isn't passed in; use a flat assumption of 200_000
    # (we calibrate sold units via hurricane_risk and the SKU's velocity).
    # NOTE: prior_season_sales accepts county_population — pass 200_000 as a
    # placeholder so the demo doesn't require pulling pop in this function.
    out: list[Shortfall] = []
    for entry in prep_plan:
        fips = entry.get('fips')
        risk = hurricane_risk_by_fips.get(fips, 0.5)
        # Convert checklist item names -> SKU ids using ITEM_TO_SKUS.
        sku_ids: list[str] = []
        for item in entry.get('stock_checklist', []):
            sku_ids.extend(ITEM_TO_SKUS.get(item, ()))
        for sku_id in sku_ids:
            sku = sku_by_id.get(sku_id)
            if sku is None:
                continue
            prior = prior_season_sales(
                entry['osm_id'], sku_id,
                sku.default_dc_stock, risk, 200_000,
            )
            target = int(round(prior * SAFETY_FACTOR))
            on_hand = current_inventory(entry['osm_id'], sku_id, target)
            short = max(0, target - on_hand)
            if short > 0:
                out.append(Shortfall(
                    dest_osm_id=entry['osm_id'],
                    dest_name=entry.get('name', ''),
                    dest_county=entry.get('county'),
                    dest_fips=fips,
                    sku_id=sku_id,
                    sku_name=sku.name,
                    item=sku.item,
                    unit=sku.unit,
                    prior_season_sold=prior,
                    target_units=target,
                    on_hand=on_hand,
                    shortfall_units=short,
                    urgency=entry.get('time_bucket', 'T-5d+'),
                ))
    return out


def compute_transfer_orders(shortfalls: list[Shortfall],
                            all_stores: list[dict]) -> list[TransferOrder]:
    '''For each shortfall, generate one Transfer Order. Source picked by:
      (1) the nearest DC with enough on-hand of this SKU; consume that stock
      (2) if no DC qualifies, the nearest store with surplus = (its on_hand
          - 1.0*its target) >= shortfall; consume that surplus
      (3) if neither, emit a TO with source_type='DC' and source_id of the
          nearest DC, but mark rationale 'no qualifying source — escalate'

    Process shortfalls in this order: most urgent first (T-6h before T-12h
    before T-24h ...), then by largest shortfall_units within a bucket. This
    way urgent stores grab DC stock first.
    '''
    urgency_rank = {'T-6h': 0, 'T-12h': 1, 'T-24h': 2, 'T-2d': 3, 'T-3d': 4,
                    'T-4d': 5, 'T-5d': 6, 'T-5d+': 7, 'Past': 99}
    ordered = sorted(
        shortfalls,
        key=lambda s: (urgency_rank.get(s.urgency, 99), -s.shortfall_units),
    )

    sku_by_id = {s.id: s for s in HURRICANE_SKUS}

    # Mutable copies of available stock so we can decrement as we allocate.
    # DC stock: {(dc_id, sku_id): units_remaining}
    dc_stock: dict[tuple[str, str], int] = {}
    for dc in DISTRIBUTION_CENTERS:
        for sku in HURRICANE_SKUS:
            dc_stock[(dc.id, sku.id)] = dc_inventory(dc.id, sku.id, sku.default_dc_stock)

    # Store surplus: {(osm_id, sku_id): surplus_units_available_to_share}
    # A store has surplus if its on_hand > 1.0 * its expected target.
    # Expected target requires prior_season_sales -> need risk per store; we
    # don't have that here. Approximate by using risk=0.7 and pop=200_000 so
    # we get a consistent surplus number per store/SKU.
    store_surplus: dict[tuple[str, str], int] = {}
    store_by_osm = {s['osm_id']: s for s in all_stores}
    for s in all_stores:
        for sku in HURRICANE_SKUS:
            prior = prior_season_sales(s['osm_id'], sku.id, sku.default_dc_stock, 0.7, 200_000)
            target = int(round(prior * SAFETY_FACTOR))
            on_hand = current_inventory(s['osm_id'], sku.id, target)
            surplus = max(0, on_hand - target)
            if surplus > 0:
                store_surplus[(s['osm_id'], sku.id)] = surplus

    R = 6371.0
    def haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
        dlat = radians(lat2 - lat1)
        dlon = radians(lon2 - lon1)
        a = sin(dlat/2)**2 + cos(radians(lat1))*cos(radians(lat2))*sin(dlon/2)**2
        return 2 * R * atan2(sqrt(a), sqrt(1-a))

    orders: list[TransferOrder] = []
    now = datetime.now(timezone.utc).isoformat()

    for i, sf in enumerate(ordered, start=1):
        # Locate dest store coords from all_stores
        dest = store_by_osm.get(sf.dest_osm_id)
        if dest is None:
            continue
        dest_lat, dest_lon = dest['lat'], dest['lon']

        # 1) Try DCs in nearest-first order with enough stock
        dcs_sorted = sorted(
            DISTRIBUTION_CENTERS,
            key=lambda d: haversine(dest_lat, dest_lon, d.lat, d.lon),
        )
        source_type, source_id, source_name, rationale = '', '', '', ''
        for dc in dcs_sorted:
            avail = dc_stock.get((dc.id, sf.sku_id), 0)
            if avail >= sf.shortfall_units:
                dc_stock[(dc.id, sf.sku_id)] = avail - sf.shortfall_units
                source_type = 'DC'
                source_id = dc.id
                source_name = dc.name
                rationale = f'Nearest DC with sufficient stock ({avail} on hand).'
                break

        # 2) Else nearest store with surplus
        if not source_type:
            candidates = []
            for (osm, sku_id), surplus in store_surplus.items():
                if sku_id != sf.sku_id or osm == sf.dest_osm_id:
                    continue
                if surplus < sf.shortfall_units:
                    continue
                src = store_by_osm.get(osm)
                if not src:
                    continue
                d = haversine(dest_lat, dest_lon, src['lat'], src['lon'])
                candidates.append((d, osm, src))
            candidates.sort(key=lambda c: c[0])
            if candidates:
                d, osm, src = candidates[0]
                store_surplus[(osm, sf.sku_id)] -= sf.shortfall_units
                source_type = 'STORE'
                source_id = osm
                source_name = f"{src.get('name','Store')} ({src.get('county','')})".strip()
                rationale = f'Nearest store with surplus ({store_surplus[(osm, sf.sku_id)] + sf.shortfall_units} units) at {round(d,1)} km.'

        # 3) Fallback: nearest DC, marked for escalation
        if not source_type:
            dc = dcs_sorted[0]
            source_type = 'DC'
            source_id = dc.id
            source_name = dc.name
            rationale = 'No qualifying source — escalate.'

        orders.append(TransferOrder(
            to_id=f'TO-{i:04d}',
            source_type=source_type,
            source_id=source_id,
            source_name=source_name,
            dest_osm_id=sf.dest_osm_id,
            dest_name=sf.dest_name,
            dest_county=sf.dest_county,
            sku_id=sf.sku_id,
            sku_name=sf.sku_name,
            units=sf.shortfall_units,
            urgency=sf.urgency,
            status='awaiting_approval',
            created_at=now,
            rationale=rationale,
        ))

    return orders
