from __future__ import annotations

import hashlib
import math

"""
Synthetic inventory and prior-season sales simulation module.
Every number generated by this module is synthetic demo data, not from any real ERP system.
"""


def _det_jitter(seed: str, lo: float, hi: float) -> float:
    '''Deterministic 'random' jitter in [lo, hi] from a string seed.
    Hash the seed with md5; take the first 8 hex chars as an int; scale to [lo, hi].'''
    h = hashlib.md5(seed.encode()).hexdigest()
    n = int(h[:8], 16) / 0xFFFFFFFF   # 0..1
    return lo + (hi - lo) * n


def prior_season_sales(osm_id: str, sku_id: str, default_dc_stock: int,
                       hurricane_risk: float, county_population: int) -> int:
    '''Synthetic units sold at this store of this SKU during the previous
    hurricane season peak window. Deterministic: same inputs always give the
    same number.'''
    base = default_dc_stock * 0.04 * hurricane_risk * math.log1p(county_population / 10000)
    jitter = _det_jitter(f'sold/{osm_id}/{sku_id}', 0.7, 1.3)
    return max(1, int(round(base * jitter)))


def current_inventory(osm_id: str, sku_id: str, target_units: int) -> int:
    '''Synthetic current on-hand. ~70% of (store, SKU) lines are at or above
    target_units; ~30% are deliberately below to make the shortfall demo light
    up. Deterministic.'''
    roll = _det_jitter(f'oh/{osm_id}/{sku_id}', 0.0, 1.0)
    if roll < 0.30:
        fill = _det_jitter(f'fill/{osm_id}/{sku_id}', 0.0, 0.70)
    else:
        fill = _det_jitter(f'fill/{osm_id}/{sku_id}', 1.0, 1.50)
    return max(0, int(round(target_units * fill)))


def dc_inventory(dc_id: str, sku_id: str, default_dc_stock: int) -> int:
    '''Synthetic DC on-hand. Most slots are at default_dc_stock; ~15% of
    (dc, SKU) combos are 'low' (10-40% of default) so the demo can also
    demonstrate the nearest-store-fallback path when the nearest DC is empty.'''
    roll = _det_jitter(f'dc/{dc_id}/{sku_id}', 0.0, 1.0)
    if roll < 0.15:
        fill = _det_jitter(f'dcfill/{dc_id}/{sku_id}', 0.10, 0.40)
    else:
        fill = _det_jitter(f'dcfill/{dc_id}/{sku_id}', 0.90, 1.30)
    return max(0, int(round(default_dc_stock * fill)))
